# config/settings.yaml
data:
  root_dir: data/
  versions:
    v1:
      train_split: 0.8
      img_size: 224
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  train:
    batch_size: 32
    shuffle: true
    num_workers: 4
  validation:
    batch_size: 16
    shuffle: false
models:
  base: 
    architecture: resnet50
    pretrained: true
    frozen_layers:
      - layer1
      - layer2
  current_version: v1
  versions:
    v1:
      num_classes: 2
      classifier:
        hidden_dims: [1024, 512]
        dropout: 0.5
      optimizer:
        type: AdamW
        lr: 0.001
        weight_decay: 0.01